name: "docs"
description: "문서화 작업"
labels: "documentation"
title: "docs: "
body:
  - type: textarea
    attributes:
      label: 개요
      placeholder: 개요를 입력하세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 상세
      placeholder: "- 상세를 입력하세요."
    validations:
      required: true
